import type { Metadata } from "next";
import {  Poppins} from "next/font/google";
import { Toaster } from "@/components/ui/toaster"


import "./globals.css";
import Script from "next/script";
const poppins = Poppins({ 
   weight : ["100", "300","500","600", "400",  "700", "900"],
   subsets: ["latin"],
   variable: "--font-poppins",
 });

export const metadata: Metadata = {
  title: "Playtok | Interactive videos as a story telling tool for brands to build trust, boost engagement, grow conversion and sales",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>{children}
      <Toaster />

      </body>
      <Script id="show" defer async src="http://localhost:5500/widget/main.js" >
      {`!function(){document.addEventListener("DOMContentLoaded",()=>{const e=document.createElement("div");e.id="vendeo-app",document.body.appendChild(e);const t=document.createElement("script");t.src="http://localhost:5500/widget/main.js?pid=669adf8637b8495eee907e51",t.async=1,t.type="module",document.body.appendChild(t),window.vendeo_flow_id="669adf8637b8495eee907e51"})}();`}
      </Script>

    </html>
  );
} 
